/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { Row } from '@rocicorp/zero'
import { createBuilder } from '@rocicorp/zero'
import type { ZeroCustomType } from 'drizzle-zero'
import type { default as zeroSchema } from './drizzle-zero.config'

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    clients: {
      name: 'clients',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'id'>,
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'userId'>,
          serverName: 'user_id',
        },
        name: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'name'>,
        },
        email: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'email'>,
        },
        street: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'street'>,
        },
        city: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'city'>,
        },
        state: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'state'>,
        },
        zip: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'zip'>,
        },
        clientStatus: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'clients',
            'clientStatus'
          >,
          serverName: 'client_status',
        },
        createdAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'createdAt'>,
          serverName: 'created_at',
        },
        updatedAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'clients', 'updatedAt'>,
          serverName: 'updated_at',
        },
      },
      primaryKey: ['id'],
    },
    invoices: {
      name: 'invoices',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'id'>,
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'userId'>,
          serverName: 'user_id',
        },
        invoiceNumber: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invoices',
            'invoiceNumber'
          >,
          serverName: 'invoice_number',
        },
        clientId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'clientId'>,
          serverName: 'client_id',
        },
        subject: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'subject'>,
        },
        issueDate: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'issueDate'>,
          serverName: 'issue_date',
        },
        dueDate: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'dueDate'>,
          serverName: 'due_date',
        },
        discount: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'discount'>,
        },
        notes: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'notes'>,
        },
        terms: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'terms'>,
        },
        invoiceStatus: {
          type: 'string',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'invoices',
            'invoiceStatus'
          >,
          serverName: 'invoice_status',
        },
        createdAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'createdAt'>,
          serverName: 'created_at',
        },
        updatedAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'invoices', 'updatedAt'>,
          serverName: 'updated_at',
        },
      },
      primaryKey: ['id'],
    },
    lineItems: {
      name: 'lineItems',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'lineItems', 'id'>,
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'lineItems', 'userId'>,
          serverName: 'user_id',
        },
        invoiceId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'lineItems',
            'invoiceId'
          >,
          serverName: 'invoice_id',
        },
        description: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'lineItems',
            'description'
          >,
        },
        quantity: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'lineItems', 'quantity'>,
        },
        amount: {
          type: 'number',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'lineItems', 'amount'>,
        },
        createdAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'lineItems',
            'createdAt'
          >,
          serverName: 'created_at',
        },
        updatedAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<
            typeof zeroSchema,
            'lineItems',
            'updatedAt'
          >,
          serverName: 'updated_at',
        },
      },
      primaryKey: ['id'],
      serverName: 'line_items',
    },
    settings: {
      name: 'settings',
      columns: {
        id: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'id'>,
        },
        userId: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'userId'>,
          serverName: 'user_id',
        },
        myName: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'myName'>,
          serverName: 'my_name',
        },
        email: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'email'>,
        },
        street: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'street'>,
        },
        city: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'city'>,
        },
        state: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'state'>,
        },
        zip: {
          type: 'string',
          optional: false,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'zip'>,
        },
        createdAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'createdAt'>,
          serverName: 'created_at',
        },
        updatedAt: {
          type: 'number',
          optional: true,
          customType: null as unknown as ZeroCustomType<typeof zeroSchema, 'settings', 'updatedAt'>,
          serverName: 'updated_at',
        },
      },
      primaryKey: ['id'],
    },
  },
  relationships: {
    clients: {
      invoices: [
        {
          sourceField: ['id'],
          destField: ['clientId'],
          destSchema: 'invoices',
          cardinality: 'many',
        },
      ],
    },
    invoices: {
      client: [
        {
          sourceField: ['clientId'],
          destField: ['id'],
          destSchema: 'clients',
          cardinality: 'one',
        },
      ],
      lineItems: [
        {
          sourceField: ['id'],
          destField: ['invoiceId'],
          destSchema: 'lineItems',
          cardinality: 'many',
        },
      ],
    },
    lineItems: {
      invoice: [
        {
          sourceField: ['invoiceId'],
          destField: ['id'],
          destSchema: 'invoices',
          cardinality: 'one',
        },
      ],
    },
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema
/**
 * Represents a row from the "clients" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Client = Row<Schema['tables']['clients']>
/**
 * Represents a row from the "invoices" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Invoice = Row<Schema['tables']['invoices']>
/**
 * Represents a row from the "lineItems" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type LineItem = Row<Schema['tables']['lineItems']>
/**
 * Represents a row from the "settings" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Setting = Row<Schema['tables']['settings']>

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema)
