import { defineSemanticTokens } from "@pandacss/dev";

const color = (base: string, dark = base) => ({
  value: {
    _dark: dark,
    base,
  },
});

export const semanticTokens = defineSemanticTokens({
  colors: {
    accent: color("{colors.robinEggBlue}"),
    accentForeground: color("{colors.blueGem}", "{colors.gray.950}"),
    authBackground: color("{colors.daisyBush}", "{colors.blueGem}"),
    authButton: color("{colors.robinEggBlue}"),
    authButtonForeground: color("{colors.daisyBush}", "{colors.gray.950}"),
    authForeground: color("{colors.white}", "{colors.gray.100}"),
    authLabel: color("{colors.goldenFizz}"),
    authLink: color("{colors.whisper}", "{colors.gray.200}"),
    avatarAccent: color("{colors.purple}", "{colors.pastelPurple}"),
    avatarForeground: color("{colors.white}", "{colors.gray.950}"),
    avatarPrimary: color("{colors.lavenderIndigo}"),
    avatarSecondary: color("{colors.daisyBush}", "{colors.blueGem}"),
    avatarTertiary: color("{colors.blueGem}", "{colors.gray.700}"),
    background: color("{colors.whisper}", "{colors.gray.950}"),
    backdrop: color("{colors.blueGem}", "{colors.gray.950}"),
    border: color("{colors.silver}", "{colors.gray.700}"),
    borderMuted: color("{colors.lightGray}", "{colors.gray.600}"),
    borderSubtle: color("{colors.fog}", "{colors.gray.800}"),
    card: color("{colors.white}", "{colors.gray.900}"),
    cardForeground: color("{colors.daisyBush}", "{colors.gray.100}"),
    destructive: color("{colors.scarlet}"),
    displayBorder: color("{colors.gray.200}", "{colors.gray.700}"),
    displayDivider: color("{colors.gray.100}", "{colors.gray.800}"),
    displayMuted: color("{colors.gray.400}"),
    displaySurface: color("{colors.gray.50}", "{colors.gray.900}"),
    displayText: color("{colors.gray.800}", "{colors.gray.100}"),
    displaySuccess: color("{colors.green.100}", "{colors.green.900}"),
    displaySuccessMuted: color("{colors.green.600}", "{colors.green.400}"),
    displaySuccessText: color("{colors.green.700}", "{colors.green.300}"),
    destructiveForeground: color("{colors.goldenFizz}", "{colors.gray.950}"),
    featureFast: color("{colors.goldenFizz}"),
    featureInfo: color("{colors.robinEggBlue}"),
    featurePrimary: color("{colors.lavenderIndigo}"),
    featureSuccess: color("{colors.caribbeanGreen}"),
    foreground: color("{colors.daisyBush}", "{colors.gray.100}"),
    foregroundInverse: color("{colors.white}", "{colors.gray.100}"),
    input: color("{colors.silver}", "{colors.gray.700}"),
    inputBackground: color("{colors.whisper}", "{colors.gray.900}"),
    inverse: color("{colors.daisyBush}", "{colors.gray.900}"),
    inverseForeground: color("{colors.goldenFizz}", "{colors.gray.100}"),
    link: color("{colors.lavenderIndigo}", "{colors.pastelPurple}"),
    linkMuted: color("{colors.stone.600}", "{colors.gray.400}"),
    muted: color("{colors.prim}", "{colors.gray.800}"),
    mutedAction: color("{colors.pastelPurple}", "{colors.gray.300}"),
    mutedActionForeground: color("{colors.blueGem}", "{colors.gray.100}"),
    metric: color("{colors.purple}", "{colors.pastelPurple}"),
    metricLabel: color("{colors.lightGray}", "{colors.gray.400}"),
    mutedForeground: color("{colors.monsoon}", "{colors.gray.400}"),
    navigationForeground: color("{colors.white}", "{colors.gray.100}"),
    navigationSurface: color("{colors.daisyBush}", "{colors.gray.900}"),
    outline: color("{colors.daisyBush}", "{colors.gray.100}"),
    overlay: color("{colors.black}"),
    popover: color("{colors.white}", "{colors.gray.900}"),
    popoverForeground: color("{colors.daisyBush}", "{colors.gray.100}"),
    primary: color("{colors.lavenderIndigo}"),
    primaryForeground: color("{colors.white}"),
    secondary: color("{colors.gallery}", "{colors.gray.800}"),
    secondaryForeground: color("{colors.blueGem}", "{colors.gray.100}"),
    skeleton: color("{colors.gray.300}", "{colors.gray.700}"),
    skeletonSubtle: color("{colors.prim}", "{colors.gray.800}"),
    statusDraft: color("{colors.pastelPurple}"),
    statusDraftForeground: color("{colors.daisyBush}", "{colors.gray.950}"),
    statusLate: color("{colors.scarlet}"),
    statusLateForeground: color("{colors.goldenFizz}"),
    statusPaid: color("{colors.pastelPurple}", "{colors.purple}"),
    statusPaidForeground: color("{colors.white}"),
    statusSent: color("{colors.robinEggBlue}"),
    statusSentForeground: color("{colors.blueGem}", "{colors.gray.950}"),
    surface: color("{colors.white}", "{colors.gray.900}"),
    surfaceMuted: color("{colors.whisper}", "{colors.gray.800}"),
    surfaceSecondary: color("{colors.gallery}", "{colors.gray.800}"),
    syntaxCode: color("{colors.caribbeanGreen}"),
    syntaxComment: color("{colors.pastelPurple}"),
    syntaxImportant: color("{colors.purple}", "{colors.pastelPurple}"),
    syntaxKeyword: color("{colors.caribbeanGreen}"),
    syntaxMuted: color("{colors.lightGray}", "{colors.gray.500}"),
    syntaxPunctuation: color("{colors.lightGray}", "{colors.gray.500}"),
    syntaxString: color("{colors.robinEggBlue}"),
    syntaxStrike: color("{colors.monsoon}", "{colors.gray.500}"),
    syntaxText: color("{colors.daisyBush}", "{colors.gray.100}"),
    syntaxTitle: color("{colors.purple}", "{colors.pastelPurple}"),
    syntaxType: color("{colors.lavenderIndigo}", "{colors.pastelPurple}"),
    textSubtle: color("{colors.pastelPurple}", "{colors.gray.400}"),
    textMuted: color("{colors.monsoon}", "{colors.gray.400}"),
    warning: color("{colors.goldenFizz}"),
    warningForeground: color("{colors.daisyBush}", "{colors.gray.950}"),
    success: color("{colors.caribbeanGreen}"),
    successForeground: color("{colors.blueGem}", "{colors.gray.950}"),
    ring: color("{colors.lavenderIndigo}", "{colors.robinEggBlue}"),
  },
});
